#include <check.h>
#include <stdlib.h>
#include <string.h>

#include "s21_decimal.h"

START_TEST(test_s21_add) {
  s21_decimal first = {{0u, 0u, 0u, 0u}, s21_NORMAL_VALUE};
  s21_decimal second = {{0u, 0u, 0u, 0u}, s21_NORMAL_VALUE};
  s21_decimal result = {{0u, 0u, 0u, 0u}, s21_NORMAL_VALUE};
  s21_decimal reference = {{0u, 0u, 0u, 0u}, s21_NORMAL_VALUE};
  result = s21_add(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 1 TEST");
  s21_from_float_to_decimal(1234, &first);
  s21_from_float_to_decimal(1234, &second);
  s21_from_float_to_decimal(2468, &reference);
  result = s21_add(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 2 TEST");
  s21_from_float_to_decimal(123456789, &first);
  s21_from_float_to_decimal(123456789, &second);
  s21_from_float_to_decimal(246913578, &reference);
  result = s21_add(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 3 TEST");
  s21_from_float_to_decimal(12345678, &first);
  s21_from_float_to_decimal(-12345678, &second);
  s21_from_float_to_decimal(0, &reference);
  result = s21_add(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 4 TEST");
  s21_from_float_to_decimal(-12345678, &first);
  s21_from_float_to_decimal(-12345678, &second);
  s21_from_int_to_decimal(-24691356, &reference);
  result = s21_add(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 5 TEST");
  s21_from_float_to_decimal(-12345678, &first);
  s21_from_float_to_decimal(12345678, &second);
  s21_from_float_to_decimal(0, &reference);
  result = s21_add(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 6 TEST");
  s21_from_int_to_decimal(12341234, &first);
  s21_from_int_to_decimal(12341234, &second);
  s21_from_int_to_decimal(24682468, &reference);
  set_scale(&first, 4);
  set_scale(&second, 4);
  set_scale(&reference, 4);
  result = s21_add(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 7 TEST");
  s21_from_int_to_decimal(-12341234, &first);
  s21_from_int_to_decimal(-12341234, &second);
  s21_from_int_to_decimal(-24682468, &reference);
  set_scale(&first, 4);
  set_scale(&second, 4);
  set_scale(&reference, 4);
  result = s21_add(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 8 TEST");
  s21_from_int_to_decimal(-12341234, &first);
  s21_from_int_to_decimal(12341234, &second);
  s21_from_int_to_decimal(0, &reference);
  set_scale(&first, 4);
  set_scale(&second, 4);
  set_scale(&reference, 4);
  result = s21_add(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 9 TEST");
  s21_from_int_to_decimal(12341234, &first);
  s21_from_int_to_decimal(-12341234, &second);
  s21_from_int_to_decimal(0, &reference);
  set_scale(&first, 4);
  set_scale(&second, 4);
  set_scale(&reference, 4);
  result = s21_add(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 10 TEST");
  s21_from_int_to_decimal(12341234, &first);
  s21_from_int_to_decimal(-12341233, &second);
  s21_from_int_to_decimal(1, &reference);
  set_scale(&first, 4);
  set_scale(&second, 4);
  set_scale(&reference, 4);
  result = s21_add(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 11 TEST");
  s21_from_int_to_decimal(-12341234, &first);
  s21_from_int_to_decimal(-12341233, &second);
  s21_from_int_to_decimal(-24682467, &reference);
  set_scale(&first, 4);
  set_scale(&second, 4);
  set_scale(&reference, 4);
  result = s21_add(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 12 TEST");
  s21_from_int_to_decimal(-12341233, &first);
  s21_from_int_to_decimal(-12341234, &second);
  s21_from_int_to_decimal(-24682467, &reference);
  set_scale(&first, 4);
  set_scale(&second, 4);
  set_scale(&reference, 4);
  result = s21_add(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 13 TEST");
  s21_from_int_to_decimal(1234, &first);
  s21_from_int_to_decimal(11234, &second);
  s21_from_int_to_decimal(113574, &reference);
  set_scale(&first, 4);
  set_scale(&second, 3);
  set_scale(&reference, 4);
  result = s21_add(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 14 TEST");
  s21_from_int_to_decimal(2, &first);
  s21_from_int_to_decimal(2, &second);
  s21_from_int_to_decimal(22, &reference);
  set_scale(&first, 4);
  set_scale(&second, 3);
  set_scale(&reference, 4);
  result = s21_add(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 15 TEST");
  s21_from_float_to_decimal(0, &first);
  s21_from_float_to_decimal(0, &second);
  s21_from_float_to_decimal(0, &reference);
  result = s21_add(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 16 TEST");
  s21_from_int_to_decimal(0, &first);
  s21_from_int_to_decimal(2, &second);
  s21_from_int_to_decimal(2, &reference);
  set_scale(&first, 4);
  set_scale(&second, 3);
  set_scale(&reference, 3);
  result = s21_add(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 17 TEST");
  s21_from_int_to_decimal(999, &first);
  s21_from_int_to_decimal(1, &second);
  s21_from_int_to_decimal(10, &reference);
  set_scale(&first, 2);
  set_scale(&second, 2);
  result = s21_add(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 18 TEST");
  s21_from_int_to_decimal(999, &first);
  s21_from_int_to_decimal(10, &second);
  s21_from_int_to_decimal(10999, &reference);
  set_scale(&first, 4);
  set_scale(&second, 1);
  set_scale(&reference, 4);
  result = s21_add(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 19 TEST");
  s21_from_float_to_decimal(3.78991, &first);
  s21_from_float_to_decimal(-3.78991, &second);
  s21_from_float_to_decimal(0, &reference);
  result = s21_add(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 20 TEST");
  s21_from_int_to_decimal(300000, &first);
  s21_from_int_to_decimal(1, &second);
  s21_from_int_to_decimal(300001, &reference);
  set_scale(&first, 5);
  set_scale(&second, 5);
  set_scale(&reference, 5);
  result = s21_add(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 21 TEST");
  s21_from_float_to_decimal(0.001, &first);
  s21_from_float_to_decimal(-0.001, &second);
  s21_from_float_to_decimal(0, &reference);
  result = s21_add(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 22 TEST");
  s21_from_float_to_decimal(10.0, &first);
  s21_from_float_to_decimal(10.0, &second);
  s21_from_float_to_decimal(20.0, &reference);
  result = s21_add(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 23 TEST");
  s21_from_float_to_decimal(0.000001, &first);
  s21_from_float_to_decimal(0.000009, &second);
  s21_from_float_to_decimal(0.00001, &reference);
  result = s21_add(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 24 TEST");
  s21_from_float_to_decimal(-0.000001, &first);
  s21_from_float_to_decimal(-0.000009, &second);
  s21_from_float_to_decimal(-0.00001, &reference);
  result = s21_add(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 25 TEST");
  s21_from_float_to_decimal(-0.000001, &first);
  s21_from_float_to_decimal(0.000009, &second);
  s21_from_float_to_decimal(0.000008, &reference);
  result = s21_add(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 26 TEST");
  s21_from_float_to_decimal(0.000001, &first);
  s21_from_float_to_decimal(-0.000009, &second);
  s21_from_float_to_decimal(-0.000008, &reference);
  result = s21_add(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 27 TEST");
  s21_from_int_to_decimal(30, &first);
  s21_from_int_to_decimal(9, &second);
  s21_from_int_to_decimal(30000009, &reference);
  set_scale(&second, 6);
  set_scale(&reference, 6);
  result = s21_add(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 28 TEST");
  s21_from_float_to_decimal(0.2, &first);
  s21_from_float_to_decimal(-0.3, &second);
  s21_from_float_to_decimal(-0.1, &reference);
  result = s21_add(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 29 TEST");
  s21_from_int_to_decimal(1000000, &first);
  s21_from_int_to_decimal(-1, &second);
  s21_from_int_to_decimal(99999999, &reference);
  set_scale(&second, 2);
  set_scale(&reference, 2);
  result = s21_add(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 30 TEST");

  // Простые тесты для краевых
  s21_decimal one = {{0u, 0u, 0u, 0u}, s21_INFINITY};
  s21_decimal two = {{0u, 0u, 0u, 0u}, s21_NEGATIVE_INFINITY};
  s21_decimal three = {{0u, 0u, 0u, 0u}, s21_NAN};
  s21_decimal normal = {{10u, 0u, 0u, 0u}, s21_NORMAL_VALUE};
  result = s21_add(one, one);
  ck_assert_msg(result.value_type == 1, "FAIL 31 TEST");
  result = s21_add(one, two);
  ck_assert_msg(result.value_type == 3, "FAIL 32 TEST");
  result = s21_add(one, three);
  ck_assert_msg(result.value_type == 3, "FAIL 33 TEST");
  result = s21_add(one, normal);
  ck_assert_msg(result.value_type == 1, "FAIL 34 TEST");
  result = s21_add(two, one);
  ck_assert_msg(result.value_type == 3, "FAIL 35 TEST");
  result = s21_add(two, two);
  ck_assert_msg(result.value_type == 2, "FAIL 36 TEST");
  result = s21_add(two, three);
  ck_assert_msg(result.value_type == 3, "FAIL 37 TEST");
  result = s21_add(two, normal);
  ck_assert_msg(result.value_type == 2, "FAIL 38 TEST");
  result = s21_add(three, one);
  ck_assert_msg(result.value_type == 3, "FAIL 39 TEST");
  result = s21_add(three, two);
  ck_assert_msg(result.value_type == 3, "FAIL 40 TEST");
  result = s21_add(three, three);
  ck_assert_msg(result.value_type == 3, "FAIL 41 TEST");
  result = s21_add(three, normal);
  ck_assert_msg(result.value_type == 3, "FAIL 42 TEST");
  result = s21_add(normal, one);
  ck_assert_msg(result.value_type == 1, "FAIL 43 TEST");
  result = s21_add(normal, two);
  ck_assert_msg(result.value_type == 2, "FAIL 44 TEST");
  result = s21_add(normal, three);
  ck_assert_msg(result.value_type == 3, "FAIL 45 TEST");
  result = s21_add(normal, normal);
  ck_assert_msg(result.value_type == 0, "FAIL 46 TEST");

  s21_from_int_to_decimal(1234567890, &first);
  s21_from_int_to_decimal(1, &second);
  s21_from_int_to_decimal(1234567891, &reference);
  set_scale(&first, 28);
  set_scale(&second, 28);
  set_scale(&reference, 28);
  result = s21_add(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 47 TEST");
  s21_decimal first_2 = {
      {0b11111111111111111111111111111111, 0b11111111111111111111111111111111,
       0b11111111111111111111111111111111, 0u},
      s21_NORMAL_VALUE};
  s21_decimal second_2 = {{0b11, 0u, 0u, 0u}, s21_NORMAL_VALUE};
  s21_decimal result_2 = {{0u, 0u, 0u, 0u}, s21_NORMAL_VALUE};
  s21_decimal reference_2 = {
      {0b11111111111111111111111111111111, 0b11111111111111111111111111111111,
       0b11111111111111111111111111111111, 0u},
      s21_NORMAL_VALUE};
  unsigned int mask = 1u << 0;
  first_2.bits[0] ^= mask;
  result_2 = s21_add(first_2, second_2);
  ck_assert_msg(result_2.value_type == 1, "FAIL 48 TEST");
}
END_TEST

START_TEST(test_s21_sub) {
  s21_decimal first = {{0u, 0u, 0u, 0u}, s21_NORMAL_VALUE};
  s21_decimal second = {{0u, 0u, 0u, 0u}, s21_NORMAL_VALUE};
  s21_decimal result = {{0u, 0u, 0u, 0u}, s21_NORMAL_VALUE};
  s21_decimal reference = {{0u, 0u, 0u, 0u}, s21_NORMAL_VALUE};
  result = s21_sub(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 1 TEST");
  ck_assert_msg(result.value_type == 0, "FAIL 1 TEST");
  s21_from_float_to_decimal(1234, &first);
  s21_from_float_to_decimal(1234, &second);
  s21_from_float_to_decimal(0, &reference);
  result = s21_sub(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 2 TEST");
  ck_assert_msg(result.value_type == 0, "FAIL 2 TEST");
  s21_from_float_to_decimal(123456789, &first);
  s21_from_float_to_decimal(123456789, &second);
  s21_from_float_to_decimal(0, &reference);
  result = s21_sub(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 3 TEST");
  ck_assert_msg(result.value_type == 0, "FAIL 3 TEST");
  s21_from_float_to_decimal(12345678, &first);
  s21_from_float_to_decimal(-12345678, &second);
  s21_from_float_to_decimal(24691356, &reference);
  result = s21_sub(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 4 TEST");
  s21_from_float_to_decimal(-12345678, &first);
  s21_from_float_to_decimal(-12345678, &second);
  s21_from_float_to_decimal(0, &reference);
  result = s21_sub(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 5 TEST");
  s21_from_float_to_decimal(-12345678, &first);
  s21_from_float_to_decimal(12345678, &second);
  s21_from_int_to_decimal(-24691356, &reference);
  result = s21_sub(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 6 TEST");
  ck_assert_msg(result.value_type == 0, "FAIL 6 TEST");
  s21_from_int_to_decimal(2, &first);
  s21_from_int_to_decimal(2, &second);
  s21_from_int_to_decimal(-18, &reference);
  set_scale(&first, 4);
  set_scale(&second, 3);
  set_scale(&reference, 4);
  result = s21_sub(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 7 TEST");
  ck_assert_msg(result.value_type == 0, "FAIL 7 TEST");
  s21_from_int_to_decimal(1, &first);
  s21_from_int_to_decimal(1, &second);
  s21_from_int_to_decimal(0, &reference);
  set_scale(&first, 27);
  set_scale(&second, 27);
  result = s21_sub(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 8 TEST");
  s21_from_int_to_decimal(1, &first);
  s21_from_int_to_decimal(1, &second);
  s21_from_int_to_decimal(-9, &reference);
  set_scale(&first, 28);
  set_scale(&second, 27);
  set_scale(&reference, 28);
  result = s21_sub(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 9 TEST");
  s21_from_int_to_decimal(12345678, &first);
  s21_from_int_to_decimal(12345678, &second);
  s21_from_int_to_decimal(-111111102, &reference);
  set_scale(&first, 28);
  set_scale(&second, 27);
  set_scale(&reference, 28);
  result = s21_sub(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 10 TEST");
  ck_assert_msg(result.value_type == 0, "FAIL 10 TEST");

  // a < b
  s21_from_int_to_decimal(100, &first);
  s21_from_int_to_decimal(175, &second);
  s21_from_int_to_decimal(-75, &reference);
  result = s21_sub(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 11 TEST");
  s21_from_int_to_decimal(100100, &first);
  s21_from_int_to_decimal(17554, &second);
  s21_from_int_to_decimal(-7544, &reference);
  set_scale(&first, 3);
  set_scale(&second, 2);
  set_scale(&reference, 2);
  result = s21_sub(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 12 TEST");
  s21_from_int_to_decimal(986422, &first);
  s21_from_int_to_decimal(1233455, &second);
  s21_from_int_to_decimal(-122359078, &reference);
  set_scale(&first, 5);
  set_scale(&second, 3);
  set_scale(&reference, 5);
  result = s21_sub(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 13 TEST");

  // a > b
  s21_from_int_to_decimal(5677734, &first);
  s21_from_int_to_decimal(12, &second);
  s21_from_int_to_decimal(5557734, &reference);
  set_scale(&first, 5);
  set_scale(&second, 1);
  set_scale(&reference, 5);
  result = s21_sub(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 14 TEST");
  s21_from_int_to_decimal(60000, &first);
  s21_from_int_to_decimal(1, &second);
  s21_from_int_to_decimal(599999, &reference);
  set_scale(&first, 4);
  set_scale(&second, 5);
  set_scale(&reference, 5);
  result = s21_sub(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 15 TEST");
  s21_from_int_to_decimal(1111111, &first);
  s21_from_int_to_decimal(999, &second);
  s21_from_int_to_decimal(-98788889, &reference);
  set_scale(&first, 6);
  set_scale(&second, 1);
  set_scale(&reference, 6);
  result = s21_sub(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 16 TEST");

  // -a > -b
  s21_from_int_to_decimal(-334522, &first);
  s21_from_int_to_decimal(-9995655, &second);
  s21_from_int_to_decimal(9661133, &reference);
  set_scale(&first, 3);
  set_scale(&second, 3);
  set_scale(&reference, 3);
  result = s21_sub(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 17 TEST");
  s21_from_int_to_decimal(-100100, &first);
  s21_from_int_to_decimal(-17554, &second);
  s21_from_int_to_decimal(174539, &reference);
  set_scale(&first, 5);
  set_scale(&second, 2);
  set_scale(&reference, 3);
  result = s21_sub(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 18 TEST");
  s21_from_int_to_decimal(-9, &first);
  s21_from_int_to_decimal(-15, &second);
  s21_from_int_to_decimal(6, &reference);
  result = s21_sub(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 19 TEST");

  // -a < -b
  s21_from_int_to_decimal(-100100, &first);
  s21_from_int_to_decimal(-17554, &second);
  s21_from_int_to_decimal(-82546, &reference);
  set_scale(&first, 3);
  set_scale(&second, 3);
  set_scale(&reference, 3);
  result = s21_sub(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 20 TEST");
  s21_from_int_to_decimal(-23, &first);
  s21_from_int_to_decimal(-3, &second);
  s21_from_int_to_decimal(-20, &reference);
  result = s21_sub(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 21 TEST");
  s21_from_int_to_decimal(-7889003, &first);
  s21_from_int_to_decimal(-9978, &second);
  s21_from_int_to_decimal(-7879025, &reference);
  set_scale(&first, 2);
  set_scale(&second, 2);
  set_scale(&reference, 2);
  result = s21_sub(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 22 TEST");

  // a > -b
  s21_from_int_to_decimal(100101, &first);
  s21_from_int_to_decimal(-17554, &second);
  s21_from_int_to_decimal(1855501, &reference);
  set_scale(&first, 3);
  set_scale(&second, 1);
  set_scale(&reference, 3);
  result = s21_sub(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 23 TEST");
  s21_from_int_to_decimal(78, &first);
  s21_from_int_to_decimal(-9, &second);
  s21_from_int_to_decimal(87, &reference);
  result = s21_sub(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 24 TEST");

  s21_from_int_to_decimal(-2147483192, &first);
  s21_from_int_to_decimal(389, &second);
  s21_from_int_to_decimal(-2147483581, &reference);
  result = s21_sub(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 26 TEST");
  s21_from_int_to_decimal(-834664, &first);
  s21_from_int_to_decimal(7089, &second);
  s21_from_int_to_decimal(-1543564, &reference);
  set_scale(&first, 3);
  set_scale(&second, 1);
  set_scale(&reference, 3);
  result = s21_sub(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 27 TEST");
  s21_from_int_to_decimal(-997765, &first);
  s21_from_int_to_decimal(7898700, &second);
  s21_from_int_to_decimal(-79984765, &reference);
  set_scale(&first, 4);
  set_scale(&second, 3);
  set_scale(&reference, 4);
  result = s21_sub(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 28 TEST");

  // 0 < . < 1
  s21_from_int_to_decimal(21474, &first);
  s21_from_int_to_decimal(-89, &second);
  s21_from_int_to_decimal(30374, &reference);
  set_scale(&first, 5);
  set_scale(&second, 3);
  set_scale(&reference, 5);
  result = s21_sub(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 29 TEST");
  s21_from_int_to_decimal(1, &first);
  s21_from_int_to_decimal(7, &second);
  s21_from_int_to_decimal(-6, &reference);
  set_scale(&first, 3);
  set_scale(&second, 3);
  set_scale(&reference, 3);
  result = s21_sub(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 30 TEST");
  s21_from_int_to_decimal(-67, &first);
  s21_from_int_to_decimal(-5, &second);
  s21_from_int_to_decimal(4933, &reference);
  set_scale(&first, 5);
  set_scale(&second, 2);
  set_scale(&reference, 5);
  result = s21_sub(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 31 TEST");

  s21_decimal one = {{0u, 0u, 0u, 0u}, s21_INFINITY};
  s21_decimal two = {{0u, 0u, 0u, 0u}, s21_NEGATIVE_INFINITY};
  s21_decimal three = {{0u, 0u, 0u, 0u}, s21_NAN};
  s21_decimal normal = {{10u, 0u, 0u, 0u}, s21_NORMAL_VALUE};
  result = s21_sub(one, one);
  ck_assert_msg(result.value_type == 3, "FAIL 31 TEST");
  result = s21_sub(one, two);
  ck_assert_msg(result.value_type == 3, "FAIL 32 TEST");
  result = s21_sub(one, three);
  ck_assert_msg(result.value_type == 3, "FAIL 33 TEST");
  result = s21_sub(one, normal);
  ck_assert_msg(result.value_type == 1, "FAIL 34 TEST");
  result = s21_sub(two, one);
  ck_assert_msg(result.value_type == 2, "FAIL 35 TEST");
  result = s21_sub(two, two);
  ck_assert_msg(result.value_type == 3, "FAIL 36 TEST");
  result = s21_sub(two, three);
  ck_assert_msg(result.value_type == 3, "FAIL 37 TEST");
  result = s21_sub(two, normal);
  ck_assert_msg(result.value_type == 2, "FAIL 38 TEST");
  result = s21_sub(three, one);
  ck_assert_msg(result.value_type == 3, "FAIL 39 TEST");
  result = s21_sub(three, two);
  ck_assert_msg(result.value_type == 3, "FAIL 40 TEST");
  result = s21_sub(three, three);
  ck_assert_msg(result.value_type == 3, "FAIL 41 TEST");
  result = s21_sub(three, normal);
  ck_assert_msg(result.value_type == 3, "FAIL 42 TEST");
  result = s21_sub(normal, one);
  ck_assert_msg(result.value_type == 1, "FAIL 43 TEST");
  result = s21_sub(normal, two);
  ck_assert_msg(result.value_type == 2, "FAIL 44 TEST");
  result = s21_sub(normal, three);
  ck_assert_msg(result.value_type == 3, "FAIL 45 TEST");
  result = s21_sub(normal, normal);
  ck_assert_msg(result.value_type == 0, "FAIL 46 TEST");
}
END_TEST

START_TEST(test_s21_div) {
  s21_decimal first = {{0u, 0u, 0u, 0u}, s21_NORMAL_VALUE};
  s21_decimal second = {{0u, 0u, 0u, 0u}, s21_NORMAL_VALUE};
  s21_decimal result = {{0u, 0u, 0u, 0u}, s21_NORMAL_VALUE};
  s21_decimal reference = {{0u, 0u, 0u, 0u}, s21_NORMAL_VALUE};
  s21_from_int_to_decimal(1234, &first);
  s21_from_int_to_decimal(2, &second);
  s21_from_int_to_decimal(617, &reference);
  result = s21_div(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 1 TEST");
  s21_from_int_to_decimal(1234, &first);
  s21_from_int_to_decimal(1, &second);
  s21_from_int_to_decimal(1234, &reference);
  result = s21_div(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 2 TEST");
  s21_from_float_to_decimal(1234, &first);
  s21_from_float_to_decimal(1234, &second);
  s21_from_int_to_decimal(1, &reference);
  result = s21_div(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 3 TEST");
  s21_from_float_to_decimal(2468, &first);
  s21_from_float_to_decimal(1234, &second);
  s21_from_float_to_decimal(2, &reference);
  result = s21_div(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 4 TEST");
  s21_from_float_to_decimal(12345678, &first);
  s21_from_float_to_decimal(2, &second);
  s21_from_float_to_decimal(6172839, &reference);
  result = s21_div(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 5 TEST");
  s21_from_float_to_decimal(0, &first);
  s21_from_float_to_decimal(0, &second);
  s21_from_float_to_decimal(0, &reference);
  result = s21_div(first, second);
  ck_assert_msg(result.value_type == 3, "FAIL 6 TEST");
  s21_from_float_to_decimal(11, &first);
  s21_from_float_to_decimal(5, &second);
  s21_from_float_to_decimal(22, &reference);
  set_scale(&reference, 1);
  result = s21_div(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 7 TEST");
  s21_from_float_to_decimal(12345678901234567.0, &first);
  s21_from_float_to_decimal(10000000.0, &second);
  s21_from_float_to_decimal(12345678901234567.0, &reference);
  set_scale(&reference, 7);
  result = s21_div(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 8 TEST");
  s21_from_float_to_decimal(12345678901234567.0, &first);
  s21_from_int_to_decimal(1000000000, &second);
  s21_from_float_to_decimal(12345678901234567.0, &reference);
  set_scale(&reference, 9);
  result = s21_div(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 9 TEST");
  s21_from_float_to_decimal(333.0, &first);
  s21_from_int_to_decimal(3, &second);
  s21_from_float_to_decimal(111.0, &reference);
  set_scale(&first, 3);
  set_scale(&second, 1);
  set_scale(&reference, 2);
  result = s21_div(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 10 TEST");
  s21_from_float_to_decimal(333333.0, &first);
  s21_from_int_to_decimal(3, &second);
  s21_from_float_to_decimal(111111.0, &reference);
  set_scale(&first, 10);
  set_scale(&second, 1);
  set_scale(&reference, 9);
  result = s21_div(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 11 TEST");
  s21_from_float_to_decimal(255.0, &first);
  s21_from_int_to_decimal(4, &second);
  s21_from_float_to_decimal(63.75, &reference);
  result = s21_div(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 12 TEST");
  s21_from_int_to_decimal(255, &first);
  s21_from_int_to_decimal(4, &second);
  s21_from_int_to_decimal(6375, &reference);
  set_scale(&first, 4);
  set_scale(&second, 4);
  set_scale(&reference, 2);
  result = s21_div(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 13 TEST");
  s21_from_int_to_decimal(255, &first);
  s21_from_int_to_decimal(4, &second);
  s21_from_int_to_decimal(6375, &reference);
  set_scale(&first, 22);
  set_scale(&second, 22);
  set_scale(&reference, 2);
  result = s21_div(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 14 TEST");
  s21_from_int_to_decimal(255, &first);
  s21_from_int_to_decimal(4, &second);
  s21_from_int_to_decimal(6375, &reference);
  set_scale(&first, 22);
  set_scale(&reference, 24);
  result = s21_div(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 15 TEST");
  s21_from_int_to_decimal(255, &first);
  s21_from_int_to_decimal(4, &second);
  s21_from_int_to_decimal(6375, &reference);
  setBit(&first, 127);
  setBit(&reference, 127);
  set_scale(&first, 22);
  set_scale(&reference, 24);
  result = s21_div(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 16 TEST");
  s21_from_int_to_decimal(104764, &first);
  s21_from_int_to_decimal(9524, &second);
  s21_from_int_to_decimal(11, &reference);
  set_scale(&first, 13);
  set_scale(&reference, 13);
  result = s21_div(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 17 TEST");
  s21_from_int_to_decimal(783876, &first);
  s21_from_int_to_decimal(65323, &second);
  s21_from_int_to_decimal(12, &reference);
  set_scale(&first, 16);
  set_scale(&reference, 16);
  result = s21_div(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 18 TEST");
  s21_from_int_to_decimal(999999, &first);
  s21_from_int_to_decimal(333333, &second);
  s21_from_int_to_decimal(3, &reference);
  set_scale(&first, 27);
  set_scale(&reference, 27);
  result = s21_div(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 19 TEST");
  s21_from_int_to_decimal(999999, &first);
  s21_from_int_to_decimal(333333, &second);
  s21_from_int_to_decimal(3, &reference);
  set_scale(&first, 6);
  set_scale(&second, 3);
  set_scale(&reference, 3);
  result = s21_div(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 20 TEST");
  s21_from_int_to_decimal(783876, &first);
  s21_from_int_to_decimal(65323, &second);
  s21_from_int_to_decimal(12, &reference);
  set_scale(&first, 6);
  set_scale(&second, 3);
  set_scale(&reference, 3);
  result = s21_div(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 21 TEST");
  s21_from_int_to_decimal(104764, &first);
  s21_from_int_to_decimal(9524, &second);
  s21_from_int_to_decimal(11, &reference);
  set_scale(&first, 9);
  set_scale(&second, 6);
  set_scale(&reference, 3);
  result = s21_div(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 22 TEST");
  s21_from_int_to_decimal(104764, &first);
  setBit(&first, 127);
  s21_from_int_to_decimal(9524, &second);
  setBit(&second, 127);
  s21_from_int_to_decimal(11, &reference);
  set_scale(&first, 9);
  set_scale(&second, 6);
  set_scale(&reference, 3);
  result = s21_div(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 23 TEST");
  s21_from_int_to_decimal(783876, &first);
  s21_from_int_to_decimal(65323, &second);
  setBit(&first, 127);
  setBit(&second, 127);
  s21_from_int_to_decimal(12, &reference);
  set_scale(&first, 6);
  set_scale(&second, 3);
  set_scale(&reference, 3);
  result = s21_div(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 24 TEST");
  s21_from_int_to_decimal(104764, &first);
  s21_from_int_to_decimal(9524, &second);
  setBit(&first, 127);
  setBit(&second, 127);
  s21_from_int_to_decimal(11, &reference);
  set_scale(&first, 13);
  set_scale(&reference, 13);
  result = s21_div(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 25 TEST");
  s21_from_int_to_decimal(783876, &first);
  s21_from_int_to_decimal(65323, &second);
  setBit(&first, 127);
  setBit(&second, 127);
  s21_from_int_to_decimal(12, &reference);
  set_scale(&first, 16);
  set_scale(&reference, 16);
  result = s21_div(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 26 TEST");
  s21_from_int_to_decimal(999999, &first);
  s21_from_int_to_decimal(333333, &second);
  setBit(&first, 127);
  setBit(&second, 127);
  s21_from_int_to_decimal(3, &reference);
  set_scale(&first, 27);
  set_scale(&reference, 27);
  result = s21_div(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 27 TEST");
  s21_from_int_to_decimal(999999, &first);
  s21_from_int_to_decimal(333333, &second);
  setBit(&first, 127);
  setBit(&second, 127);
  s21_from_int_to_decimal(3, &reference);
  set_scale(&first, 6);
  set_scale(&second, 3);
  set_scale(&reference, 3);
  result = s21_div(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 28 TEST");
  s21_from_int_to_decimal(104764, &first);
  setBit(&first, 127);
  s21_from_int_to_decimal(9524, &second);
  s21_from_int_to_decimal(11, &reference);
  setBit(&reference, 127);
  set_scale(&first, 9);
  set_scale(&second, 6);
  set_scale(&reference, 3);
  result = s21_div(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 29 TEST");
  s21_from_int_to_decimal(783876, &first);
  s21_from_int_to_decimal(65323, &second);
  setBit(&first, 127);
  s21_from_int_to_decimal(12, &reference);
  setBit(&reference, 127);
  set_scale(&first, 6);
  set_scale(&second, 3);
  set_scale(&reference, 3);
  result = s21_div(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 30 TEST");
  s21_from_int_to_decimal(104764, &first);
  s21_from_int_to_decimal(9524, &second);
  setBit(&first, 127);
  s21_from_int_to_decimal(11, &reference);
  setBit(&reference, 127);
  set_scale(&first, 13);
  set_scale(&reference, 13);
  result = s21_div(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 31 TEST");
  s21_from_int_to_decimal(783876, &first);
  s21_from_int_to_decimal(65323, &second);
  setBit(&second, 127);
  s21_from_int_to_decimal(12, &reference);
  setBit(&reference, 127);
  set_scale(&first, 16);
  set_scale(&reference, 16);
  result = s21_div(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 32 TEST");
  s21_from_int_to_decimal(999999, &first);
  s21_from_int_to_decimal(333333, &second);
  setBit(&second, 127);
  s21_from_int_to_decimal(3, &reference);
  setBit(&reference, 127);
  set_scale(&first, 27);
  set_scale(&reference, 27);
  result = s21_div(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 33 TEST");
  s21_from_int_to_decimal(999999, &first);
  s21_from_int_to_decimal(333333, &second);
  setBit(&second, 127);
  s21_from_int_to_decimal(3, &reference);
  setBit(&reference, 127);
  set_scale(&first, 6);
  set_scale(&second, 3);
  set_scale(&reference, 3);
  result = s21_div(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 34 TEST");
  s21_from_int_to_decimal(783876, &first);
  s21_from_int_to_decimal(783876, &second);
  s21_from_int_to_decimal(1, &reference);
  set_scale(&first, 16);
  set_scale(&reference, 16);
  result = s21_div(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 35 TEST");
  s21_from_int_to_decimal(999999, &first);
  s21_from_int_to_decimal(999999, &second);
  setBit(&first, 127);
  setBit(&second, 127);
  s21_from_int_to_decimal(1, &reference);
  set_scale(&first, 27);
  set_scale(&reference, 27);
  result = s21_div(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 36 TEST");
  ck_assert_msg(result.value_type == 0, "FAIL 36 TEST");
  s21_from_int_to_decimal(104764, &first);
  s21_from_int_to_decimal(104764, &second);
  s21_from_int_to_decimal(1, &reference);
  set_scale(&first, 6);
  set_scale(&second, 3);
  set_scale(&reference, 3);
  result = s21_div(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 37 TEST");
  s21_from_int_to_decimal(3, &first);
  s21_from_int_to_decimal(5, &second);
  s21_from_int_to_decimal(6, &reference);
  set_scale(&first, 1);
  set_scale(&second, 1);
  set_scale(&reference, 1);
  result = s21_div(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 38 TEST");
  s21_from_int_to_decimal(9, &first);
  s21_from_int_to_decimal(9, &second);
  s21_from_int_to_decimal(1, &reference);
  set_scale(&first, 1);
  set_scale(&second, 1);
  set_scale(&reference, 0);
  result = s21_div(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 39 TEST");
  s21_from_int_to_decimal(5, &first);
  s21_from_int_to_decimal(8, &second);
  s21_from_int_to_decimal(625, &reference);
  set_scale(&first, 1);
  set_scale(&second, 1);
  set_scale(&reference, 3);
  result = s21_div(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 40 TEST");

  s21_decimal one = {{0u, 0u, 0u, 0u}, s21_INFINITY};
  s21_decimal two = {{0u, 0u, 0u, 0u}, s21_NEGATIVE_INFINITY};
  s21_decimal three = {{0u, 0u, 0u, 0u}, s21_NAN};
  s21_decimal normal = {{10u, 0u, 0u, 0u}, s21_NORMAL_VALUE};
  s21_decimal zero = {{0u, 0u, 0u, 0u}, s21_NORMAL_VALUE};
  result = s21_div(one, one);
  ck_assert_msg(result.value_type == 3, "FAIL 41 TEST");
  result = s21_div(one, two);
  ck_assert_msg(result.value_type == 3, "FAIL 42 TEST");
  result = s21_div(one, three);
  ck_assert_msg(result.value_type == 3, "FAIL 43 TEST");
  result = s21_div(one, normal);
  ck_assert_msg(result.value_type == 1, "FAIL 44 TEST");
  result = s21_div(two, one);
  ck_assert_msg(result.value_type == 3, "FAIL 45 TEST");
  result = s21_div(two, two);
  ck_assert_msg(result.value_type == 3, "FAIL 46 TEST");
  result = s21_div(two, three);
  ck_assert_msg(result.value_type == 3, "FAIL 47 TEST");
  result = s21_div(two, normal);
  ck_assert_msg(result.value_type == 2, "FAIL 48 TEST");
  result = s21_div(three, one);
  ck_assert_msg(result.value_type == 3, "FAIL 49 TEST");
  result = s21_div(three, two);
  ck_assert_msg(result.value_type == 3, "FAIL 50 TEST");
  result = s21_div(three, three);
  ck_assert_msg(result.value_type == 3, "FAIL 51 TEST");
  result = s21_div(three, normal);
  ck_assert_msg(result.value_type == 3, "FAIL 52 TEST");
  result = s21_div(normal, one);
  ck_assert_msg(result.value_type == 0, "FAIL 53 TEST");
  ck_assert_msg(!s21_is_equal(result, zero) == 1, "FAIL 53 TEST");
  result = s21_div(normal, two);
  ck_assert_msg(result.value_type == 0, "FAIL 54 TEST");
  ck_assert_msg(!s21_is_equal(result, zero) == 1, "FAIL 54 TEST");
  result = s21_div(normal, three);
  ck_assert_msg(result.value_type == 3, "FAIL 55 TEST");
  result = s21_div(normal, normal);
  ck_assert_msg(result.value_type == 0, "FAIL 56 TEST");
  result = s21_div(zero, one);
  ck_assert_msg(result.value_type == 0, "FAIL 57 TEST");
  ck_assert_msg(!s21_is_equal(result, zero) == 1, "FAIL 57 TEST");
  result = s21_div(zero, two);
  ck_assert_msg(result.value_type == 0, "FAIL 58 TEST");
  ck_assert_msg(!s21_is_equal(result, zero) == 1, "FAIL 58 TEST");
  result = s21_div(two, zero);
  ck_assert_msg(result.value_type == 3, "FAIL 59 TEST");
  result = s21_div(three, zero);
  ck_assert_msg(result.value_type == 3, "FAIL 60 TEST");
  result = s21_div(normal, zero);
  ck_assert_msg(result.value_type == 1, "FAIL 61 TEST");
  result = s21_div(zero, normal);
  ck_assert_msg(result.value_type == 0, "FAIL 62 TEST");
  ck_assert_msg(!s21_is_equal(result, zero) == 1, "FAIL 62 TEST");
  setBit(&normal, 127);
  result = s21_div(normal, zero);
  ck_assert_msg(result.value_type == 2, "FAIL 63 TEST");
}
END_TEST

START_TEST(test_s21_mod) {
  s21_decimal first = {{0u, 0u, 0u, 0u}, s21_NORMAL_VALUE};
  s21_decimal second = {{0u, 0u, 0u, 0u}, s21_NORMAL_VALUE};
  s21_decimal result = {{0u, 0u, 0u, 0u}, s21_NORMAL_VALUE};
  s21_decimal reference = {{0u, 0u, 0u, 0u}, s21_NORMAL_VALUE};
  s21_from_float_to_decimal(10.0, &first);
  s21_from_float_to_decimal(10.0, &second);
  s21_from_float_to_decimal(0.0, &reference);
  result = s21_mod(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 1 TEST");
  s21_from_float_to_decimal(10.0, &first);
  s21_from_float_to_decimal(1.0, &second);
  s21_from_float_to_decimal(0.0, &reference);
  result = s21_mod(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 2 TEST");
  s21_from_float_to_decimal(16899936.0, &first);
  s21_from_float_to_decimal(5.0, &second);
  s21_from_float_to_decimal(1.0, &reference);
  result = s21_mod(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 3 TEST");
  s21_from_float_to_decimal(789.0, &first);
  s21_from_float_to_decimal(5.0, &second);
  s21_from_float_to_decimal(4.0, &reference);
  result = s21_mod(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 4 TEST");
  s21_from_float_to_decimal(-17.0, &first);
  s21_from_float_to_decimal(5.0, &second);
  s21_from_float_to_decimal(-2.0, &reference);
  result = s21_mod(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 5 TEST");
  s21_from_float_to_decimal(8933.0, &first);
  s21_from_float_to_decimal(888.0, &second);
  s21_from_float_to_decimal(53.0, &reference);
  set_scale(&first, 2);
  set_scale(&second, 2);
  set_scale(&reference, 2);
  result = s21_mod(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 6 TEST");

  s21_decimal inf = {{0u, 0u, 0u, 0u}, s21_INFINITY};
  s21_decimal negative_inf = {{0u, 0u, 0u, 0u}, s21_NEGATIVE_INFINITY};
  s21_decimal nan = {{0u, 0u, 0u, 0u}, s21_NAN};
  s21_decimal zero = {{0u, 0u, 0u, 0u}, s21_NORMAL_VALUE};
  result = s21_mod(inf, inf);
  ck_assert_msg(result.value_type == 3, "FAIL 7 TEST");
  result = s21_mod(negative_inf, inf);
  ck_assert_msg(result.value_type == 3, "FAIL 8 TEST");
  result = s21_mod(negative_inf, negative_inf);
  ck_assert_msg(result.value_type == 3, "FAIL 9 TEST");
  result = s21_mod(inf, negative_inf);
  ck_assert_msg(result.value_type == 3, "FAIL 10 TEST");
  result = s21_mod(nan, negative_inf);
  ck_assert_msg(result.value_type == 3, "FAIL 11 TEST");
  result = s21_mod(nan, nan);
  ck_assert_msg(result.value_type == 3, "FAIL 12 TEST");
  result = s21_mod(inf, nan);
  ck_assert_msg(result.value_type == 3, "FAIL 13 TEST");
  result = s21_mod(negative_inf, nan);
  ck_assert_msg(result.value_type == 3, "FAIL 14 TEST");
  result = s21_mod(nan, inf);
  ck_assert_msg(result.value_type == 3, "FAIL 15 TEST");
  s21_from_float_to_decimal(8933.0, &first);
  result = s21_mod(first, inf);
  ck_assert_msg(result.value_type == 0, "FAIL 16 TEST");
  ck_assert_msg(s21_is_equal(result, first) == 0, "FAIL 16 TEST");
  s21_from_float_to_decimal(8933.0, &first);
  result = s21_mod(first, negative_inf);
  ck_assert_msg(result.value_type == 0, "FAIL 17 TEST");
  ck_assert_msg(s21_is_equal(result, first) == 0, "FAIL 17 TEST");
  s21_from_float_to_decimal(8933.0, &first);
  result = s21_mod(inf, first);
  ck_assert_msg(result.value_type == 3, "FAIL 18 TEST");
  s21_from_float_to_decimal(8933.0, &first);
  result = s21_mod(negative_inf, first);
  ck_assert_msg(result.value_type == 3, "FAIL 19 TEST");
  result = s21_mod(inf, zero);
  ck_assert_msg(result.value_type == 3, "FAIL 20 TEST");
  result = s21_mod(zero, zero);
  ck_assert_msg(result.value_type == 0, "FAIL 21 TEST");
  ck_assert_msg(s21_is_equal(result, zero) == 0, "FAIL 21 TEST");
}
END_TEST

START_TEST(test_s21_mul) {
  s21_decimal first = {{0u, 0u, 0u, 0u}, s21_NORMAL_VALUE};
  s21_decimal second = {{0u, 0u, 0u, 0u}, s21_NORMAL_VALUE};
  s21_decimal result = {{0u, 0u, 0u, 0u}, s21_NORMAL_VALUE};
  s21_decimal reference = {{0u, 0u, 0u, 0u}, s21_NORMAL_VALUE};
  s21_from_int_to_decimal(1234, &first);
  s21_from_int_to_decimal(1234, &second);
  s21_from_int_to_decimal(1522756, &reference);
  result = s21_mul(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 1 TEST");
  s21_from_int_to_decimal(1234, &first);
  s21_from_int_to_decimal(1234, &second);
  s21_from_int_to_decimal(1522756, &reference);
  set_scale(&first, 4);
  set_scale(&second, 4);
  set_scale(&reference, 8);
  result = s21_mul(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 2 TEST");
  s21_from_int_to_decimal(1234, &first);
  s21_from_int_to_decimal(1234, &second);
  s21_from_int_to_decimal(1522756, &reference);
  set_scale(&first, 4);
  set_scale(&second, 3);
  set_scale(&reference, 7);
  result = s21_mul(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 3 TEST");
  s21_from_int_to_decimal(1, &first);
  s21_from_int_to_decimal(1, &second);
  s21_from_int_to_decimal(1, &reference);
  set_scale(&first, 4);
  set_scale(&second, 3);
  set_scale(&reference, 7);
  result = s21_mul(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 4 TEST");
  s21_from_int_to_decimal(10000, &first);
  s21_from_int_to_decimal(10000, &second);
  s21_from_int_to_decimal(10, &reference);
  set_scale(&first, 4);
  set_scale(&second, 3);
  result = s21_mul(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 5 TEST");
  s21_from_int_to_decimal(556, &first);
  s21_from_int_to_decimal(876, &second);
  s21_from_int_to_decimal(487056, &reference);
  set_scale(&first, 1);
  set_scale(&second, 1);
  set_scale(&reference, 2);
  result = s21_mul(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 6 TEST");
  s21_from_int_to_decimal(-556, &first);
  s21_from_int_to_decimal(876, &second);
  s21_from_int_to_decimal(-487056, &reference);
  set_scale(&first, 1);
  set_scale(&second, 1);
  set_scale(&reference, 2);
  result = s21_mul(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 7 TEST");
  s21_from_int_to_decimal(556, &first);
  s21_from_int_to_decimal(-876, &second);
  s21_from_int_to_decimal(-487056, &reference);
  set_scale(&first, 1);
  set_scale(&second, 1);
  set_scale(&reference, 2);
  result = s21_mul(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 8 TEST");
  s21_from_int_to_decimal(-556, &first);
  s21_from_int_to_decimal(-876, &second);
  s21_from_int_to_decimal(487056, &reference);
  set_scale(&first, 1);
  set_scale(&second, 1);
  set_scale(&reference, 2);
  result = s21_mul(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 9 TEST");
  s21_from_int_to_decimal(0, &first);
  s21_from_int_to_decimal(-876, &second);
  s21_from_int_to_decimal(0, &reference);
  set_scale(&first, 1);
  set_scale(&second, 1);
  set_scale(&reference, 2);
  result = s21_mul(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 10 TEST");
  s21_from_int_to_decimal(0, &first);
  s21_from_int_to_decimal(0, &second);
  s21_from_int_to_decimal(0, &reference);
  set_scale(&first, 1);
  set_scale(&second, 1);
  set_scale(&reference, 2);
  result = s21_mul(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 11 TEST");
  s21_from_int_to_decimal(1234, &first);
  s21_from_int_to_decimal(0, &second);
  s21_from_int_to_decimal(0, &reference);
  set_scale(&first, 1);
  set_scale(&second, 1);
  set_scale(&reference, 2);
  result = s21_mul(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 12 TEST");
  s21_from_int_to_decimal(-1234, &first);
  s21_from_int_to_decimal(0, &second);
  s21_from_int_to_decimal(0, &reference);
  set_scale(&first, 1);
  set_scale(&second, 1);
  set_scale(&reference, 2);
  result = s21_mul(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 13 TEST");
  s21_from_int_to_decimal(1, &first);
  s21_from_int_to_decimal(1, &second);
  s21_from_int_to_decimal(1, &reference);
  set_scale(&first, 10);
  set_scale(&second, 10);
  set_scale(&reference, 20);
  result = s21_mul(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 14 TEST");
  s21_from_int_to_decimal(1234, &first);
  s21_from_int_to_decimal(11, &second);
  s21_from_int_to_decimal(13574, &reference);
  set_scale(&first, 10);
  set_scale(&second, 10);
  set_scale(&reference, 20);
  result = s21_mul(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 15 TEST");
  s21_from_int_to_decimal(1234, &first);
  setBit(&first, 127);
  s21_from_int_to_decimal(11, &second);
  setBit(&second, 127);
  s21_from_int_to_decimal(13574, &reference);
  set_scale(&first, 10);
  set_scale(&second, 10);
  set_scale(&reference, 20);
  result = s21_mul(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 16 TEST");
  s21_from_int_to_decimal(11, &first);
  s21_from_int_to_decimal(1234, &second);
  s21_from_int_to_decimal(13574, &reference);
  set_scale(&first, 10);
  set_scale(&second, 10);
  set_scale(&reference, 20);
  result = s21_mul(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 17 TEST");
  ck_assert_msg(result.value_type == 0, "FAIL 17 TEST");
  s21_from_int_to_decimal(11, &first);
  setBit(&first, 127);
  s21_from_int_to_decimal(1234, &second);
  setBit(&second, 127);
  s21_from_int_to_decimal(13574, &reference);
  set_scale(&first, 10);
  set_scale(&second, 10);
  set_scale(&reference, 20);
  result = s21_mul(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 18 TEST");
  s21_from_int_to_decimal(15, &first);
  s21_from_int_to_decimal(11, &second);
  s21_from_int_to_decimal(165, &reference);
  set_scale(&first, 10);
  set_scale(&second, 10);
  set_scale(&reference, 20);
  result = s21_mul(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 19 TEST");
  s21_from_int_to_decimal(15, &first);
  setBit(&first, 127);
  s21_from_int_to_decimal(11, &second);
  setBit(&second, 127);
  s21_from_int_to_decimal(165, &reference);
  set_scale(&first, 10);
  set_scale(&second, 10);
  set_scale(&reference, 20);
  result = s21_mul(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 20 TEST");
  s21_from_int_to_decimal(11, &first);
  s21_from_int_to_decimal(15, &second);
  s21_from_int_to_decimal(165, &reference);
  set_scale(&first, 10);
  set_scale(&second, 10);
  set_scale(&reference, 20);
  result = s21_mul(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 21 TEST");
  s21_from_int_to_decimal(11, &first);
  setBit(&first, 127);
  s21_from_int_to_decimal(15, &second);
  setBit(&second, 127);
  s21_from_int_to_decimal(165, &reference);
  set_scale(&first, 10);
  set_scale(&second, 10);
  set_scale(&reference, 20);
  result = s21_mul(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 22 TEST");
  s21_from_int_to_decimal(555, &first);
  s21_from_int_to_decimal(101, &second);
  s21_from_int_to_decimal(56055, &reference);
  set_scale(&first, 9);
  set_scale(&second, 5);
  set_scale(&reference, 14);
  result = s21_mul(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 23 TEST");
  s21_from_int_to_decimal(555, &first);
  setBit(&first, 127);
  s21_from_int_to_decimal(101, &second);
  setBit(&second, 127);
  s21_from_int_to_decimal(56055, &reference);
  set_scale(&first, 9);
  set_scale(&second, 5);
  set_scale(&reference, 14);
  result = s21_mul(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 24 TEST");
  s21_from_int_to_decimal(101, &first);
  s21_from_int_to_decimal(555, &second);
  s21_from_int_to_decimal(56055, &reference);
  set_scale(&first, 5);
  set_scale(&second, 9);
  set_scale(&reference, 14);
  result = s21_mul(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 25 TEST");
  s21_from_int_to_decimal(101, &first);
  setBit(&first, 127);
  s21_from_int_to_decimal(555, &second);
  setBit(&second, 127);
  s21_from_int_to_decimal(56055, &reference);
  set_scale(&first, 5);
  set_scale(&second, 9);
  set_scale(&reference, 14);
  result = s21_mul(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 26 TEST");
  s21_from_int_to_decimal(15, &first);
  s21_from_int_to_decimal(11, &second);
  setBit(&second, 127);
  s21_from_int_to_decimal(165, &reference);
  setBit(&reference, 127);
  set_scale(&first, 10);
  set_scale(&second, 10);
  set_scale(&reference, 20);
  result = s21_mul(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 27 TEST");
  s21_from_int_to_decimal(11, &first);
  setBit(&first, 127);
  s21_from_int_to_decimal(15, &second);
  s21_from_int_to_decimal(165, &reference);
  setBit(&reference, 127);
  set_scale(&first, 10);
  set_scale(&second, 10);
  set_scale(&reference, 20);
  result = s21_mul(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 28 TEST");
  s21_from_int_to_decimal(11, &first);
  s21_from_int_to_decimal(15, &second);
  setBit(&second, 127);
  s21_from_int_to_decimal(165, &reference);
  setBit(&reference, 127);
  set_scale(&first, 10);
  set_scale(&second, 10);
  set_scale(&reference, 20);
  result = s21_mul(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 29 TEST");
  s21_from_int_to_decimal(555, &first);
  setBit(&first, 127);
  s21_from_int_to_decimal(101, &second);
  s21_from_int_to_decimal(56055, &reference);
  setBit(&reference, 127);
  set_scale(&first, 9);
  set_scale(&second, 5);
  set_scale(&reference, 14);
  result = s21_mul(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 30 TEST");
  s21_from_int_to_decimal(555, &first);
  s21_from_int_to_decimal(101, &second);
  setBit(&second, 127);
  s21_from_int_to_decimal(56055, &reference);
  setBit(&reference, 127);
  set_scale(&first, 9);
  set_scale(&second, 5);
  set_scale(&reference, 14);
  result = s21_mul(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 31 TEST");
  s21_from_int_to_decimal(101, &first);
  setBit(&first, 127);
  s21_from_int_to_decimal(555, &second);
  s21_from_int_to_decimal(56055, &reference);
  setBit(&reference, 127);
  set_scale(&first, 5);
  set_scale(&second, 9);
  set_scale(&reference, 14);
  result = s21_mul(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 32 TEST");
  s21_from_int_to_decimal(101, &first);
  s21_from_int_to_decimal(555, &second);
  setBit(&second, 127);
  s21_from_int_to_decimal(56055, &reference);
  setBit(&reference, 127);
  set_scale(&first, 5);
  set_scale(&second, 9);
  set_scale(&reference, 14);
  result = s21_mul(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 33 TEST");
  s21_from_int_to_decimal(24323, &first);
  s21_from_int_to_decimal(24323, &second);
  s21_from_int_to_decimal(591608329, &reference);
  set_scale(&first, 3);
  set_scale(&second, 5);
  set_scale(&reference, 8);
  result = s21_mul(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 34 TEST");
  s21_from_int_to_decimal(7532, &first);
  setBit(&first, 127);
  s21_from_int_to_decimal(7532, &second);
  setBit(&second, 127);
  s21_from_int_to_decimal(56731024, &reference);
  set_scale(&first, 2);
  set_scale(&second, 1);
  set_scale(&reference, 3);
  result = s21_mul(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 35 TEST");
  s21_from_int_to_decimal(9999, &first);
  s21_from_int_to_decimal(9999, &second);
  s21_from_int_to_decimal(99980001, &reference);
  set_scale(&first, 0);
  set_scale(&second, 1);
  set_scale(&reference, 1);
  result = s21_mul(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 36 TEST");
  s21_from_int_to_decimal(1, &first);
  s21_from_int_to_decimal(1, &second);
  s21_from_int_to_decimal(1, &reference);
  set_scale(&first, 1);
  set_scale(&second, 1);
  set_scale(&reference, 2);
  result = s21_mul(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 37 TEST");
  s21_from_int_to_decimal(7, &first);
  s21_from_int_to_decimal(9, &second);
  s21_from_int_to_decimal(63, &reference);
  set_scale(&first, 1);
  set_scale(&second, 1);
  set_scale(&reference, 2);
  result = s21_mul(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 38 TEST");
  s21_from_int_to_decimal(3, &first);
  s21_from_int_to_decimal(5, &second);
  s21_from_int_to_decimal(15, &reference);
  set_scale(&first, 1);
  set_scale(&second, 1);
  set_scale(&reference, 2);
  result = s21_mul(first, second);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 39 TEST");

  s21_decimal one = {{0u, 0u, 0u, 0u}, s21_INFINITY};
  s21_decimal two = {{0u, 0u, 0u, 0u}, s21_NEGATIVE_INFINITY};
  s21_decimal three = {{0u, 0u, 0u, 0u}, s21_NAN};
  s21_decimal normal = {{10u, 0u, 0u, 0u}, s21_NORMAL_VALUE};
  s21_decimal zero = {{0u, 0u, 0u, 0u}, s21_NORMAL_VALUE};
  result = s21_mul(one, one);
  ck_assert_msg(result.value_type == 1, "FAIL 31 TEST");
  result = s21_mul(one, two);
  ck_assert_msg(result.value_type == 2, "FAIL 32 TEST");
  result = s21_mul(one, three);
  ck_assert_msg(result.value_type == 3, "FAIL 33 TEST");
  result = s21_mul(one, normal);
  ck_assert_msg(result.value_type == 1, "FAIL 34 TEST");
  result = s21_mul(two, one);
  ck_assert_msg(result.value_type == 2, "FAIL 35 TEST");
  result = s21_mul(two, two);
  ck_assert_msg(result.value_type == 1, "FAIL 36 TEST");
  result = s21_mul(two, three);
  ck_assert_msg(result.value_type == 3, "FAIL 37 TEST");
  result = s21_mul(two, normal);
  ck_assert_msg(result.value_type == 2, "FAIL 38 TEST");
  result = s21_mul(three, one);
  ck_assert_msg(result.value_type == 3, "FAIL 39 TEST");
  result = s21_mul(three, two);
  ck_assert_msg(result.value_type == 3, "FAIL 40 TEST");
  result = s21_mul(three, three);
  ck_assert_msg(result.value_type == 3, "FAIL 41 TEST");
  result = s21_mul(three, normal);
  ck_assert_msg(result.value_type == 3, "FAIL 42 TEST");
  result = s21_mul(normal, one);
  ck_assert_msg(result.value_type == 1, "FAIL 43 TEST");
  result = s21_mul(normal, two);
  ck_assert_msg(result.value_type == 2, "FAIL 44 TEST");
  result = s21_mul(normal, three);
  ck_assert_msg(result.value_type == 3, "FAIL 45 TEST");
  result = s21_mul(normal, normal);
  ck_assert_msg(result.value_type == 0, "FAIL 46 TEST");
  result = s21_mul(zero, one);
  ck_assert_msg(result.value_type == 3, "FAIL 47 TEST");
  result = s21_mul(zero, two);
  ck_assert_msg(result.value_type == 3, "FAIL 48 TEST");
  result = s21_mul(two, zero);
  ck_assert_msg(result.value_type == 3, "FAIL 49 TEST");
  result = s21_mul(three, zero);
  ck_assert_msg(result.value_type == 3, "FAIL 50 TEST");
}
END_TEST

START_TEST(test_s21_floor) {
  s21_decimal first = {{0u, 0u, 0u, 0u}, s21_NORMAL_VALUE};
  s21_decimal result = {{0u, 0u, 0u, 0u}, s21_NORMAL_VALUE};
  s21_decimal reference = {{0u, 0u, 0u, 0u}, s21_NORMAL_VALUE};
  s21_from_int_to_decimal(1234, &first);
  s21_from_int_to_decimal(0, &reference);
  set_scale(&first, 4);
  result = s21_floor(first);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 1 TEST");
  s21_from_int_to_decimal(99999, &first);
  s21_from_int_to_decimal(0, &reference);
  set_scale(&first, 5);
  result = s21_floor(first);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 2 TEST");
  s21_from_int_to_decimal(00001, &first);
  s21_from_int_to_decimal(0, &reference);
  set_scale(&first, 5);
  result = s21_floor(first);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 3 TEST");
  s21_from_int_to_decimal(-1234, &first);
  s21_from_int_to_decimal(-1, &reference);
  set_scale(&first, 4);
  result = s21_floor(first);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 4 TEST");
  s21_from_int_to_decimal(-99999, &first);
  s21_from_int_to_decimal(-1, &reference);
  set_scale(&first, 5);
  result = s21_floor(first);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 5 TEST");
  s21_from_int_to_decimal(-00001, &first);
  s21_from_int_to_decimal(-1, &reference);
  set_scale(&first, 5);
  result = s21_floor(first);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 6 TEST");
  s21_from_int_to_decimal(12340000, &first);
  s21_from_int_to_decimal(1234, &reference);
  set_scale(&first, 4);
  result = s21_floor(first);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 7 TEST");
  s21_from_int_to_decimal(12349999, &first);
  s21_from_int_to_decimal(1234, &reference);
  set_scale(&first, 4);
  result = s21_floor(first);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 8 TEST");
  s21_from_int_to_decimal(123400001, &first);
  s21_from_int_to_decimal(1234, &reference);
  set_scale(&first, 5);
  result = s21_floor(first);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 9 TEST");
  s21_from_int_to_decimal(-12340000, &first);
  s21_from_int_to_decimal(-1235, &reference);
  set_scale(&first, 4);
  result = s21_floor(first);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 10 TEST");
  s21_from_int_to_decimal(-12349999, &first);
  s21_from_int_to_decimal(-1235, &reference);
  set_scale(&first, 4);
  result = s21_floor(first);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 11 TEST");
  s21_from_int_to_decimal(-123400001, &first);
  s21_from_int_to_decimal(-1235, &reference);
  set_scale(&first, 5);
  result = s21_floor(first);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 12 TEST");
}
END_TEST

START_TEST(test_s21_round) {
  s21_decimal first = {{0u, 0u, 0u, 0u}, s21_NORMAL_VALUE};
  s21_decimal result = {{0u, 0u, 0u, 0u}, s21_NORMAL_VALUE};
  s21_decimal reference = {{0u, 0u, 0u, 0u}, s21_NORMAL_VALUE};
  s21_from_int_to_decimal(1234, &first);
  s21_from_int_to_decimal(0, &reference);
  set_scale(&first, 4);
  result = s21_round(first);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 1 TEST");
  s21_from_int_to_decimal(99999, &first);
  s21_from_int_to_decimal(1, &reference);
  set_scale(&first, 5);
  result = s21_round(first);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 2 TEST");
  s21_from_int_to_decimal(00001, &first);
  s21_from_int_to_decimal(0, &reference);
  set_scale(&first, 5);
  result = s21_round(first);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 3 TEST");
  s21_from_int_to_decimal(-1234, &first);
  s21_from_int_to_decimal(0, &reference);
  set_scale(&first, 4);
  result = s21_round(first);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 4 TEST");
  s21_from_int_to_decimal(-99999, &first);
  s21_from_int_to_decimal(-1, &reference);
  set_scale(&first, 5);
  result = s21_round(first);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 5 TEST");
  s21_from_int_to_decimal(-00001, &first);
  s21_from_int_to_decimal(0, &reference);
  set_scale(&first, 5);
  result = s21_round(first);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 6 TEST");
  s21_from_int_to_decimal(12340000, &first);
  s21_from_int_to_decimal(1234, &reference);
  set_scale(&first, 4);
  result = s21_round(first);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 7 TEST");
  s21_from_int_to_decimal(12349999, &first);
  s21_from_int_to_decimal(1235, &reference);
  set_scale(&first, 4);
  result = s21_round(first);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 8 TEST");
  s21_from_int_to_decimal(123400001, &first);
  s21_from_int_to_decimal(1234, &reference);
  set_scale(&first, 5);
  result = s21_round(first);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 9 TEST");
  s21_from_int_to_decimal(-12340000, &first);
  s21_from_int_to_decimal(-1234, &reference);
  set_scale(&first, 4);
  result = s21_round(first);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 10 TEST");
  s21_from_int_to_decimal(-12349999, &first);
  s21_from_int_to_decimal(-1235, &reference);
  set_scale(&first, 4);
  result = s21_round(first);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 11 TEST");
  s21_from_int_to_decimal(-123400001, &first);
  s21_from_int_to_decimal(-1234, &reference);
  set_scale(&first, 5);
  result = s21_round(first);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 12 TEST");

  s21_decimal inf = {{0u, 0u, 0u, 0u}, s21_INFINITY};
  s21_decimal negative_inf = {{0u, 0u, 0u, 0u}, s21_NEGATIVE_INFINITY};
  s21_decimal nan = {{0u, 0u, 0u, 0u}, s21_NAN};
  result = s21_round(inf);
  ck_assert_msg(result.value_type == 1, "FAIL 13 TEST");
}
END_TEST

START_TEST(test_s21_from_int_to_decimal) {
  s21_decimal first = {{0u, 0u, 0u, 0u}, s21_NORMAL_VALUE};
  s21_decimal reference1 = {{10u, 0u, 0u, 0u}, s21_NORMAL_VALUE};
  s21_from_int_to_decimal(10, &first);
  ck_assert_msg(s21_is_equal(first, reference1) == 0, "FAIL 1 TEST");
  s21_decimal reference2 = {{0u, 0u, 0u, 0u}, s21_NORMAL_VALUE};
  s21_from_int_to_decimal(0, &first);
  ck_assert_msg(s21_is_equal(first, reference2) == 0, "FAIL 2 TEST");
  s21_decimal reference3 = {{34567654u, 0u, 0u, 0u}, s21_NORMAL_VALUE};
  s21_from_int_to_decimal(34567654, &first);
  ck_assert_msg(s21_is_equal(first, reference3) == 0, "FAIL 3 TEST");
  s21_decimal reference4 = {{0b11, 0u, 0u, 0u}, s21_NORMAL_VALUE};
  s21_from_int_to_decimal(3, &first);
  ck_assert_msg(s21_is_equal(first, reference4) == 0, "FAIL 4 TEST");
  s21_decimal reference5 = {{23u, 0u, 0u, 0u}, s21_NORMAL_VALUE};
  setBit(&reference5, 127);
  s21_from_int_to_decimal(-23, &first);
  ck_assert_msg(s21_is_equal(first, reference5) == 0, "FAIL 5 TEST");
  s21_decimal reference6 = {{1234567890u, 0u, 0u, 0u}, s21_NORMAL_VALUE};
  setBit(&reference6, 127);
  s21_from_int_to_decimal(-1234567890, &first);
  ck_assert_msg(s21_is_equal(first, reference6) == 0, "FAIL 6 TEST");
  s21_decimal reference7 = {{0u, 0u, 0u, 0u}, s21_NORMAL_VALUE};
  setBit(&reference7, 127);
  s21_from_int_to_decimal(0, &first);
  ck_assert_msg(s21_is_equal(first, reference7) == 0, "FAIL 7 TEST");
}
END_TEST

START_TEST(test_s21_from_decimal_to_int) {
  int reference = 0;
  int convert = 0;
  s21_decimal first = {{0u, 0u, 0u, 0u}, s21_NORMAL_VALUE};
  s21_from_decimal_to_int(first, &convert);
  ck_assert_msg(reference - convert == 0, "FAIL 1 TEST");
  reference = 10;
  s21_decimal second = {{10u, 0u, 0u, 0u}, s21_NORMAL_VALUE};
  s21_from_decimal_to_int(second, &convert);
  ck_assert_msg(reference - convert == 0, "FAIL 2 TEST");
  reference = -10;
  s21_decimal third = {{10u, 0u, 0u, 0u}, s21_NORMAL_VALUE};
  setBit(&third, 127);
  s21_from_decimal_to_int(third, &convert);
  ck_assert_msg(reference - convert == 0, "FAIL 3 TEST");
  reference = 2147483647;
  s21_decimal fourth = {{2147483647u, 0u, 0u, 0u}, s21_NORMAL_VALUE};
  s21_from_decimal_to_int(fourth, &convert);
  ck_assert_msg(reference - convert == 0, "FAIL 4 TEST");
  reference = -2147483647;
  s21_decimal fifth = {{2147483647u, 0u, 0u, 0u}, s21_NORMAL_VALUE};
  setBit(&fifth, 127);
  s21_from_decimal_to_int(fifth, &convert);
  ck_assert_msg(reference - convert == 0, "FAIL 5 TEST");
  reference = 1;
  s21_decimal sixth = {{12u, 0u, 0u, 0u}, s21_NORMAL_VALUE};
  set_scale(&sixth, 1);
  s21_from_decimal_to_int(sixth, &convert);
  ck_assert_msg(reference - convert == 0, "FAIL 6 TEST");
  reference = 0;
  s21_decimal seventh = {{12u, 0u, 0u, 0u}, s21_NORMAL_VALUE};
  set_scale(&seventh, 5);
  s21_from_decimal_to_int(seventh, &convert);
  ck_assert_msg(reference - convert == 0, "FAIL 7 TEST");
  reference = -1;
  s21_decimal eightth = {{12u, 0u, 0u, 0u}, s21_NORMAL_VALUE};
  set_scale(&eightth, 1);
  setBit(&eightth, 127);
  s21_from_decimal_to_int(eightth, &convert);
  ck_assert_msg(reference - convert == 0, "FAIL 8 TEST");
  reference = 0;
  s21_decimal nineth = {{12u, 0u, 0u, 0u}, s21_NORMAL_VALUE};
  set_scale(&nineth, 5);
  setBit(&nineth, 127);
  s21_from_decimal_to_int(nineth, &convert);
  ck_assert_msg(reference - convert == 0,
                "FAIL 9 TEST");  // ? как он должен обработать перевод -0.01 в 0
  // (-0 или просто 0)
  reference = 0;
  s21_decimal nineth_2 = {{99u, 0u, 0u, 0u}, s21_NORMAL_VALUE};
  set_scale(&nineth_2, 2);
  setBit(&nineth_2, 127);
  s21_from_decimal_to_int(nineth_2, &convert);
  ck_assert_msg(reference - convert == 0, "FAIL 10 TEST");
  reference = 0;
  s21_decimal nineth_3 = {{91234121u, 0u, 0u, 0u}, s21_NORMAL_VALUE};
  set_scale(&nineth_3, 27);
  setBit(&nineth_3, 127);
  s21_from_decimal_to_int(nineth_3, &convert);
  ck_assert_msg(reference - convert == 0, "FAIL 11 TEST");

  s21_decimal inf = {{0u, 0u, 0u, 0u}, s21_INFINITY};
  s21_decimal neg_inf = {{0u, 0u, 0u, 0u}, s21_NEGATIVE_INFINITY};
  s21_decimal nan = {{0u, 0u, 0u, 0u}, s21_NAN};
  s21_decimal zero = {{0u, 0u, 0u, 0u}, s21_NORMAL_VALUE};
  ck_assert_msg(s21_from_decimal_to_int(inf, &convert) == 1, "FAIL 12 TEST");
  ck_assert_msg(s21_from_decimal_to_int(neg_inf, &convert) == 1,
                "FAIL 13 TEST");
  ck_assert_msg(s21_from_decimal_to_int(nan, &convert) == 1, "FAIL 14 TEST");
  ck_assert_msg(s21_from_decimal_to_int(zero, &convert) == 0, "FAIL 15 TEST");
}
END_TEST

START_TEST(test_s21_from_float_to_decimal) {
  s21_decimal first = {{0u, 0u, 0u, 0u}, s21_NORMAL_VALUE};
  s21_decimal reference1 = {{1012u, 0u, 0u, 0u}, s21_NORMAL_VALUE};
  set_scale(&reference1, 2);
  s21_from_float_to_decimal(10.12, &first);
  ck_assert_msg(s21_is_equal(first, reference1) == 0, "FAIL 1 TEST");
  s21_decimal reference2 = {{1012u, 0u, 0u, 0u}, s21_NORMAL_VALUE};
  set_scale(&reference2, 4);
  s21_from_float_to_decimal(0.1012, &first);
  ck_assert_msg(s21_is_equal(first, reference2) == 0, "FAIL 2 TEST");
  s21_decimal reference3 = {{3456u, 0u, 0u, 0u}, s21_NORMAL_VALUE};
  set_scale(&reference3, 0);
  s21_from_float_to_decimal(3456.0, &first);
  ck_assert_msg(s21_is_equal(first, reference3) == 0, "FAIL 3 TEST");
  s21_decimal reference4 = {{1012u, 0u, 0u, 0u}, s21_NORMAL_VALUE};
  set_scale(&reference4, 2);
  setBit(&reference4, 127);
  s21_from_float_to_decimal(-10.12, &first);
  ck_assert_msg(s21_is_equal(first, reference4) == 0, "FAIL 4 TEST");
  s21_decimal reference5 = {{1012u, 0u, 0u, 0u}, s21_NORMAL_VALUE};
  set_scale(&reference5, 4);
  setBit(&reference5, 127);
  s21_from_float_to_decimal(-0.1012, &first);
  ck_assert_msg(s21_is_equal(first, reference5) == 0, "FAIL 5 TEST");
  s21_decimal reference6 = {{3456u, 0u, 0u, 0u}, s21_NORMAL_VALUE};
  set_scale(&reference6, 0);
  setBit(&reference6, 127);
  s21_from_float_to_decimal(-3456.0, &first);
  ck_assert_msg(s21_is_equal(first, reference6) == 0, "FAIL 6 TEST");
  s21_decimal reference7 = {{1u, 0u, 0u, 0u}, s21_NORMAL_VALUE};
  set_scale(&reference7, 1);
  s21_from_float_to_decimal(0.1, &first);
  ck_assert_msg(s21_is_equal(first, reference7) == 0, "FAIL 7 TEST");
  s21_decimal reference8 = {{1u, 0u, 0u, 0u}, s21_NORMAL_VALUE};
  set_scale(&reference8, 1);
  setBit(&reference8, 127);
  s21_from_float_to_decimal(-0.1, &first);
  ck_assert_msg(s21_is_equal(first, reference8) == 0, "FAIL 8 TEST");
  s21_decimal reference9 = {{1u, 0u, 0u, 0u}, s21_NORMAL_VALUE};
  set_scale(&reference9, 3);
  s21_from_float_to_decimal(0.001, &first);
  ck_assert_msg(s21_is_equal(first, reference9) == 0, "FAIL 9 TEST");
  s21_decimal reference10 = {{1u, 0u, 0u, 0u}, s21_NORMAL_VALUE};
  set_scale(&reference10, 3);
  setBit(&reference10, 127);
  s21_from_float_to_decimal(-0.001, &first);
  ck_assert_msg(s21_is_equal(first, reference10) == 0, "FAIL 10 TEST");
  s21_decimal reference11 = {{534u, 0u, 0u, 0u}, s21_NORMAL_VALUE};
  set_scale(&reference11, 6);
  s21_from_float_to_decimal(0.000534, &first);
  ck_assert_msg(s21_is_equal(first, reference11) == 0, "FAIL 11 TEST");
  s21_decimal reference12 = {{534u, 0u, 0u, 0u}, s21_NORMAL_VALUE};
  set_scale(&reference12, 6);
  setBit(&reference12, 127);
  s21_from_float_to_decimal(-0.000534, &first);
  ck_assert_msg(s21_is_equal(first, reference12) == 0, "FAIL 12 TEST");
  float a1 = 0.0 / 0.0;
  ck_assert_msg(s21_from_float_to_decimal(a1, &first) == 1, "FAIL 13 TEST");
  ck_assert_msg(first.value_type == 3, "FAIL 13 TEST");
  ck_assert_msg(s21_from_float_to_decimal(0x7f7fffff, &first) == 0,
                "FAIL 14 TEST");
  a1 = 1.0 / 0.0;
  ck_assert_msg(s21_from_float_to_decimal(a1, &first) == 1, "FAIL 15 TEST");
  ck_assert_msg(first.value_type == 1, "FAIL 15 TEST");
  a1 *= -1.0;
  ck_assert_msg(s21_from_float_to_decimal(a1, &first) == 1, "FAIL 15 TEST");
  ck_assert_msg(first.value_type == 2, "FAIL 15 TEST");
}
END_TEST

START_TEST(test_s21_from_decimal_to_float) {
  float reference = 10.12;
  float convert = 0;
  s21_decimal one = {{1012u, 0u, 0u, 0u}, s21_NORMAL_VALUE};
  set_scale(&one, 2);
  s21_from_decimal_to_float(one, &convert);
  ck_assert_msg(reference - convert == 0, "FAIL 1 TEST");
  reference = 0.1012;
  s21_decimal two = {{1012u, 0u, 0u, 0u}, s21_NORMAL_VALUE};
  set_scale(&two, 4);
  s21_from_decimal_to_float(two, &convert);
  ck_assert_msg(reference - convert == 0, "FAIL 2 TEST");
  reference = 3456.0;
  s21_decimal three = {{3456u, 0u, 0u, 0u}, s21_NORMAL_VALUE};
  set_scale(&three, 0);
  s21_from_decimal_to_float(three, &convert);
  ck_assert_msg(reference - convert == 0, "FAIL 3 TEST");
  reference = -10.12;
  s21_decimal four = {{1012u, 0u, 0u, 0u}, s21_NORMAL_VALUE};
  set_scale(&four, 2);
  setBit(&four, 127);
  s21_from_decimal_to_float(four, &convert);
  ck_assert_msg(reference - convert == 0, "FAIL 4 TEST");
  reference = -0.1012;
  s21_decimal five = {{1012u, 0u, 0u, 0u}, s21_NORMAL_VALUE};
  set_scale(&five, 4);
  setBit(&five, 127);
  s21_from_decimal_to_float(five, &convert);
  ck_assert_msg(reference - convert == 0, "FAIL 5 TEST");
  reference = -3456.0;
  s21_decimal six = {{3456u, 0u, 0u, 0u}, s21_NORMAL_VALUE};
  set_scale(&six, 0);
  setBit(&six, 127);
  s21_from_decimal_to_float(six, &convert);
  ck_assert_msg(reference - convert == 0, "FAIL 6 TEST");
  reference = 0.1;
  s21_decimal seven = {{1u, 0u, 0u, 0u}, s21_NORMAL_VALUE};
  set_scale(&seven, 1);
  // setBit(&four, 127);
  s21_from_decimal_to_float(seven, &convert);
  ck_assert_msg(reference - convert == 0, "FAIL 7 TEST");
  reference = -0.1;
  s21_decimal eight = {{1u, 0u, 0u, 0u}, s21_NORMAL_VALUE};
  set_scale(&eight, 1);
  setBit(&eight, 127);
  s21_from_decimal_to_float(eight, &convert);
  ck_assert_msg(reference - convert == 0, "FAIL 8 TEST");
  reference = 0.001;
  s21_decimal nine = {{1u, 0u, 0u, 0u}, s21_NORMAL_VALUE};
  set_scale(&nine, 3);
  s21_from_decimal_to_float(nine, &convert);
  ck_assert_msg(reference - convert == 0, "FAIL 9 TEST");
  reference = -0.001;
  s21_decimal ten = {{1u, 0u, 0u, 0u}, s21_NORMAL_VALUE};
  set_scale(&ten, 3);
  setBit(&ten, 127);
  s21_from_decimal_to_float(ten, &convert);
  ck_assert_msg(reference - convert == 0, "FAIL 10 TEST");
  reference = 0.000534;
  s21_decimal eleven = {{534u, 0u, 0u, 0u}, s21_NORMAL_VALUE};
  set_scale(&eleven, 6);
  // setBit(&four, 127);
  s21_from_decimal_to_float(eleven, &convert);
  ck_assert_msg(reference - convert == 0, "FAIL 11 TEST");
  reference = -0.000534;
  s21_decimal twelve = {{534u, 0u, 0u, 0u}, s21_NORMAL_VALUE};
  set_scale(&twelve, 6);
  setBit(&twelve, 127);
  s21_from_decimal_to_float(twelve, &convert);
  ck_assert_msg(reference - convert == 0, "FAIL 12 TEST");
}
END_TEST

START_TEST(test_s21_is_less_is_greater) {
  s21_decimal first = {{0u, 0u, 0u, 0u}, s21_NORMAL_VALUE};
  s21_decimal second = {{0u, 0u, 0u, 0u}, s21_NORMAL_VALUE};
  s21_decimal result = {{0u, 0u, 0u, 0u}, s21_NORMAL_VALUE};
  s21_decimal result1 = {{0u, 0u, 0u, 0u}, s21_NORMAL_VALUE};
  s21_from_int_to_decimal(101, &first);
  s21_from_int_to_decimal(555, &second);
  s21_from_int_to_decimal(s21_is_less(first, second), &result1);
  ck_assert_msg(s21_is_equal(result1, result) == 0, "FAIL 1 TEST");
  s21_from_int_to_decimal(555, &first);
  s21_from_int_to_decimal(101, &second);
  s21_from_int_to_decimal(s21_is_less(first, second), &result1);
  ck_assert_msg(s21_is_equal(result1, result) == 1, "FAIL 2 TEST");
  s21_from_int_to_decimal(53818, &first);
  setBit(&first, 127);
  s21_from_int_to_decimal(7948486, &second);
  s21_from_int_to_decimal(s21_is_less(first, second), &result1);
  ck_assert_msg(s21_is_equal(result1, result) == 0, "FAIL 3 TEST");
  s21_from_int_to_decimal(2147483647, &first);
  s21_from_int_to_decimal(2147483647, &second);
  setBit(&second, 127);
  s21_from_int_to_decimal(s21_is_less(first, second), &result1);
  ck_assert_msg(s21_is_equal(result1, result) == 1, "FAIL 4 TEST");
  s21_from_int_to_decimal(101, &first);
  s21_from_int_to_decimal(555, &second);
  s21_from_int_to_decimal(s21_is_greater(first, second), &result1);
  ck_assert_msg(s21_is_equal(result1, result) == 1, "FAIL 5 TEST");
  s21_from_int_to_decimal(555, &first);
  s21_from_int_to_decimal(101, &second);
  s21_from_int_to_decimal(s21_is_greater(first, second), &result1);
  ck_assert_msg(s21_is_equal(result1, result) == 0, "FAIL 6 TEST");
  s21_from_int_to_decimal(53818, &first);
  setBit(&first, 127);
  s21_from_int_to_decimal(7948486, &second);
  s21_from_int_to_decimal(s21_is_greater(first, second), &result1);
  ck_assert_msg(s21_is_equal(result1, result) == 1, "FAIL 7 TEST");
  s21_from_int_to_decimal(2147483647, &first);
  s21_from_int_to_decimal(2147483647, &second);
  setBit(&second, 127);
  s21_from_int_to_decimal(s21_is_greater(first, second), &result1);
  ck_assert_msg(s21_is_equal(result1, result) == 0, "FAIL 8 TEST");

  // ГАЙД ДЛЯ РОМЫ
  s21_decimal inf = {{0u, 0u, 0u, 0u}, s21_INFINITY};
  s21_decimal negative_inf = {{0u, 0u, 0u, 0u}, s21_NEGATIVE_INFINITY};
  s21_decimal nan = {{0u, 0u, 0u, 0u}, s21_NAN};
  s21_decimal zero = {{0u, 0u, 0u, 0u}, s21_NORMAL_VALUE};
  int intResult = -1;
  intResult = s21_is_less(inf, inf);
  ck_assert_msg(intResult == 1, "FAIL 9 TEST");
  intResult = s21_is_less(negative_inf, inf);
  ck_assert_msg(intResult == 0, "FAIL 10 TEST");
  intResult = s21_is_less(negative_inf, negative_inf);
  ck_assert_msg(intResult == 1, "FAIL 11 TEST");
  intResult = s21_is_less(inf, negative_inf);
  ck_assert_msg(intResult == 1, "FAIL 12 TEST");
  intResult = s21_is_less(zero, negative_inf);
  ck_assert_msg(intResult == 1, "FAIL 13 TEST");
  intResult = s21_is_less(negative_inf, zero);
  ck_assert_msg(intResult == 0, "FAIL 14 TEST");
  intResult = s21_is_less(zero, inf);
  ck_assert_msg(intResult == 0, "FAIL 15 TEST");
  intResult = s21_is_less(negative_inf, nan);
  ck_assert_msg(intResult == 1, "FAIL 16 TEST");
  intResult = s21_is_less(nan, negative_inf);
  ck_assert_msg(intResult == 1, "FAIL 17 TEST");
  intResult = s21_is_less(nan, nan);
  ck_assert_msg(intResult == 1, "FAIL 18 TEST");
  intResult = s21_is_less(inf, nan);
  ck_assert_msg(intResult == 1, "FAIL 19 TEST");
  intResult = s21_is_less(nan, inf);
  ck_assert_msg(intResult == 1, "FAIL 20 TEST");
  intResult = s21_is_less(zero, nan);
  ck_assert_msg(intResult == 1, "FAIL 21 TEST");
  intResult = s21_is_less(nan, zero);
  ck_assert_msg(intResult == 1, "FAIL 22 TEST");
  intResult = s21_is_less(inf, zero);
  ck_assert_msg(intResult == 1, "FAIL 23 TEST");

  intResult = -1;
  intResult = s21_is_greater(inf, inf);
  ck_assert_msg(intResult == 1, "FAIL 24 TEST");
  intResult = s21_is_greater(negative_inf, inf);
  ck_assert_msg(intResult == 1, "FAIL 25 TEST");
  intResult = s21_is_greater(negative_inf, negative_inf);
  ck_assert_msg(intResult == 1, "FAIL 26 TEST");
  intResult = s21_is_greater(inf, negative_inf);
  ck_assert_msg(intResult == 0, "FAIL 27 TEST");
  intResult = s21_is_greater(zero, negative_inf);
  ck_assert_msg(intResult == 0, "FAIL 28 TEST");
  intResult = s21_is_greater(negative_inf, zero);
  ck_assert_msg(intResult == 1, "FAIL 29 TEST");
  intResult = s21_is_greater(zero, inf);
  ck_assert_msg(intResult == 1, "FAIL 30 TEST");
  intResult = s21_is_greater(negative_inf, nan);
  ck_assert_msg(intResult == 1, "FAIL 31 TEST");
  intResult = s21_is_greater(nan, negative_inf);
  ck_assert_msg(intResult == 1, "FAIL 32 TEST");
  intResult = s21_is_greater(nan, nan);
  ck_assert_msg(intResult == 1, "FAIL 33 TEST");
  intResult = s21_is_greater(inf, nan);
  ck_assert_msg(intResult == 1, "FAIL 34 TEST");
  intResult = s21_is_greater(nan, inf);
  ck_assert_msg(intResult == 1, "FAIL 35 TEST");
  intResult = s21_is_greater(zero, nan);
  ck_assert_msg(intResult == 1, "FAIL 36 TEST");
  intResult = s21_is_greater(nan, zero);
  ck_assert_msg(intResult == 1, "FAIL 37 TEST");
  intResult = s21_is_greater(inf, zero);
  ck_assert_msg(intResult == 0, "FAIL 38 TEST");
}
END_TEST

START_TEST(test_s21_is_lessOrEqual_is_greaterOrEqual) {
  s21_decimal first = {{0u, 0u, 0u, 0u}, s21_NORMAL_VALUE};
  s21_decimal second = {{0u, 0u, 0u, 0u}, s21_NORMAL_VALUE};
  s21_decimal result = {{0u, 0u, 0u, 0u}, s21_NORMAL_VALUE};
  s21_decimal result1 = {{0u, 0u, 0u, 0u}, s21_NORMAL_VALUE};
  s21_from_int_to_decimal(101, &first);
  s21_from_int_to_decimal(555, &second);
  s21_from_int_to_decimal(s21_is_greater_or_equal(first, second), &result1);
  ck_assert_msg(s21_is_equal(result1, result) == 1, "FAIL 1 TEST");
  s21_from_int_to_decimal(555, &first);
  s21_from_int_to_decimal(555, &second);
  s21_from_int_to_decimal(s21_is_greater_or_equal(first, second), &result1);
  ck_assert_msg(s21_is_equal(result1, result) == 0, "FAIL 2 TEST");
  s21_from_int_to_decimal(53818, &first);
  setBit(&first, 127);
  s21_from_int_to_decimal(7948486, &second);
  s21_from_int_to_decimal(s21_is_greater_or_equal(first, second), &result1);
  ck_assert_msg(s21_is_equal(result1, result) == 1, "FAIL 3 TEST");
  s21_from_int_to_decimal(2147483647, &first);
  s21_from_int_to_decimal(2147483647, &second);
  setBit(&second, 127);
  s21_from_int_to_decimal(s21_is_greater_or_equal(first, second), &result1);
  ck_assert_msg(s21_is_equal(result1, result) == 0, "FAIL 4 TEST");
  s21_from_int_to_decimal(101, &first);
  s21_from_int_to_decimal(555, &second);
  s21_from_int_to_decimal(s21_is_less_or_equal(first, second), &result1);
  ck_assert_msg(s21_is_equal(result1, result) == 0, "FAIL 5 TEST");
  s21_from_int_to_decimal(555, &first);
  s21_from_int_to_decimal(555, &second);
  s21_from_int_to_decimal(s21_is_less_or_equal(first, second), &result1);
  ck_assert_msg(s21_is_equal(result1, result) == 0, "FAIL 6 TEST");
  s21_from_int_to_decimal(53818, &first);
  setBit(&first, 127);
  s21_from_int_to_decimal(7948486, &second);
  s21_from_int_to_decimal(s21_is_less_or_equal(first, second), &result1);
  ck_assert_msg(s21_is_equal(result1, result) == 0, "FAIL 7 TEST");
  s21_from_int_to_decimal(2147483647, &first);
  s21_from_int_to_decimal(2147483647, &second);
  setBit(&second, 127);
  s21_from_int_to_decimal(s21_is_less_or_equal(first, second), &result1);
  ck_assert_msg(s21_is_equal(result1, result) == 1, "FAIL 8 TEST");
  s21_from_int_to_decimal(2147483647, &first);
  s21_from_int_to_decimal(2147483647, &second);
  setBit(&second, 127);
  s21_from_int_to_decimal(s21_is_equal(first, second), &result1);
  ck_assert_msg(s21_is_equal(result1, result) == 1, "FAIL 9 TEST");
  s21_from_int_to_decimal(2147483647, &first);
  s21_from_int_to_decimal(2147483647, &second);
  s21_from_int_to_decimal(s21_is_equal(first, second), &result1);
  ck_assert_msg(s21_is_equal(result1, result) == 0, "FAIL 10 TEST");
  s21_from_int_to_decimal(2147483647, &first);
  s21_from_int_to_decimal(2147, &second);
  s21_from_int_to_decimal(s21_is_equal(first, second), &result1);
  ck_assert_msg(s21_is_equal(result1, result) == 1, "FAIL 11 TEST");
  s21_from_int_to_decimal(2147483647, &first);
  s21_from_int_to_decimal(2147483647, &second);
  setBit(&second, 127);
  s21_from_int_to_decimal(s21_is_not_equal(first, second), &result1);
  ck_assert_msg(s21_is_equal(result1, result) == 0, "FAIL 12 TEST");
  s21_from_int_to_decimal(2147483647, &first);
  s21_from_int_to_decimal(2147483647, &second);
  s21_from_int_to_decimal(s21_is_not_equal(first, second), &result1);
  ck_assert_msg(s21_is_equal(result1, result) == 1, "FAIL 13 TEST");
  s21_from_int_to_decimal(2147483647, &first);
  s21_from_int_to_decimal(2147, &second);
  s21_from_int_to_decimal(s21_is_not_equal(first, second), &result1);
  ck_assert_msg(s21_is_equal(result1, result) == 0, "FAIL 14 TEST");

  s21_decimal inf = {{0u, 0u, 0u, 0u}, s21_INFINITY};
  s21_decimal negative_inf = {{0u, 0u, 0u, 0u}, s21_NEGATIVE_INFINITY};
  s21_decimal nan = {{0u, 0u, 0u, 0u}, s21_NAN};
  s21_decimal zero = {{0u, 0u, 0u, 0u}, s21_NORMAL_VALUE};
  int intResult = -1;
  intResult = s21_is_less_or_equal(inf, inf);
  ck_assert_msg(intResult == 1, "FAIL 15 TEST");
  intResult = s21_is_less_or_equal(negative_inf, inf);
  ck_assert_msg(intResult == 0, "FAIL 16 TEST");
  intResult = s21_is_less_or_equal(negative_inf, negative_inf);
  ck_assert_msg(intResult == 1, "FAIL 17 TEST");
  intResult = s21_is_less_or_equal(inf, negative_inf);
  ck_assert_msg(intResult == 1, "FAIL 18 TEST");
  intResult = s21_is_less_or_equal(zero, negative_inf);
  ck_assert_msg(intResult == 1, "FAIL 19 TEST");
  intResult = s21_is_less_or_equal(negative_inf, zero);
  ck_assert_msg(intResult == 0, "FAIL 20 TEST");
  intResult = s21_is_less_or_equal(zero, inf);
  ck_assert_msg(intResult == 0, "FAIL 21 TEST");
  intResult = s21_is_less_or_equal(negative_inf, nan);
  ck_assert_msg(intResult == 1, "FAIL 22 TEST");
  intResult = s21_is_less_or_equal(nan, negative_inf);
  ck_assert_msg(intResult == 1, "FAIL 23 TEST");
  intResult = s21_is_less_or_equal(nan, nan);
  ck_assert_msg(intResult == 1, "FAIL 24 TEST");
  intResult = s21_is_less_or_equal(inf, nan);
  ck_assert_msg(intResult == 1, "FAIL 25 TEST");
  intResult = s21_is_less_or_equal(nan, inf);
  ck_assert_msg(intResult == 1, "FAIL 26 TEST");
  intResult = s21_is_less_or_equal(zero, nan);
  ck_assert_msg(intResult == 1, "FAIL 27 TEST");
  intResult = s21_is_less_or_equal(nan, zero);
  ck_assert_msg(intResult == 1, "FAIL 28 TEST");
  intResult = s21_is_less_or_equal(inf, zero);
  ck_assert_msg(intResult == 1, "FAIL 29 TEST");

  intResult = -1;
  intResult = s21_is_greater_or_equal(inf, inf);
  ck_assert_msg(intResult == 1, "FAIL 30 TEST");
  intResult = s21_is_greater_or_equal(negative_inf, inf);
  ck_assert_msg(intResult == 1, "FAIL 31 TEST");
  intResult = s21_is_greater_or_equal(negative_inf, negative_inf);
  ck_assert_msg(intResult == 1, "FAIL 32 TEST");
  intResult = s21_is_greater_or_equal(inf, negative_inf);
  ck_assert_msg(intResult == 0, "FAIL 33 TEST");
  intResult = s21_is_greater_or_equal(zero, negative_inf);
  ck_assert_msg(intResult == 0, "FAIL 34 TEST");
  intResult = s21_is_greater_or_equal(negative_inf, zero);
  ck_assert_msg(intResult == 1, "FAIL 35 TEST");
  intResult = s21_is_greater_or_equal(zero, inf);
  ck_assert_msg(intResult == 1, "FAIL 36 TEST");
  intResult = s21_is_greater_or_equal(negative_inf, nan);
  ck_assert_msg(intResult == 1, "FAIL 37 TEST");
  intResult = s21_is_greater_or_equal(nan, negative_inf);
  ck_assert_msg(intResult == 1, "FAIL 38 TEST");
  intResult = s21_is_greater_or_equal(nan, nan);
  ck_assert_msg(intResult == 1, "FAIL 39 TEST");
  intResult = s21_is_greater_or_equal(inf, nan);
  ck_assert_msg(intResult == 1, "FAIL 40 TEST");
  intResult = s21_is_greater_or_equal(nan, inf);
  ck_assert_msg(intResult == 1, "FAIL 41 TEST");
  intResult = s21_is_greater_or_equal(zero, nan);
  ck_assert_msg(intResult == 1, "FAIL 42 TEST");
  intResult = s21_is_greater_or_equal(nan, zero);
  ck_assert_msg(intResult == 1, "FAIL 43 TEST");
  intResult = s21_is_greater_or_equal(inf, zero);
  ck_assert_msg(intResult == 0, "FAIL 44 TEST");

  intResult = -1;
  intResult = s21_is_equal(inf, inf);
  ck_assert_msg(intResult == 1, "FAIL 30 TEST");
  intResult = s21_is_equal(negative_inf, inf);
  ck_assert_msg(intResult == 1, "FAIL 31 TEST");
  intResult = s21_is_equal(negative_inf, negative_inf);
  ck_assert_msg(intResult == 1, "FAIL 32 TEST");
  intResult = s21_is_equal(inf, negative_inf);
  ck_assert_msg(intResult == 1, "FAIL 33 TEST");
  intResult = s21_is_equal(zero, negative_inf);
  ck_assert_msg(intResult == 1, "FAIL 34 TEST");
  intResult = s21_is_equal(negative_inf, zero);
  ck_assert_msg(intResult == 1, "FAIL 35 TEST");
  intResult = s21_is_equal(zero, inf);
  ck_assert_msg(intResult == 1, "FAIL 36 TEST");
  intResult = s21_is_equal(negative_inf, nan);
  ck_assert_msg(intResult == 1, "FAIL 37 TEST");
  intResult = s21_is_equal(nan, negative_inf);
  ck_assert_msg(intResult == 1, "FAIL 38 TEST");
  intResult = s21_is_equal(nan, nan);
  ck_assert_msg(intResult == 1, "FAIL 39 TEST");
  intResult = s21_is_equal(inf, nan);
  ck_assert_msg(intResult == 1, "FAIL 40 TEST");
  intResult = s21_is_equal(nan, inf);
  ck_assert_msg(intResult == 1, "FAIL 41 TEST");
  intResult = s21_is_equal(zero, nan);
  ck_assert_msg(intResult == 1, "FAIL 42 TEST");
  intResult = s21_is_equal(nan, zero);
  ck_assert_msg(intResult == 1, "FAIL 43 TEST");
  intResult = s21_is_equal(inf, zero);
  ck_assert_msg(intResult == 1, "FAIL 44 TEST");
}
END_TEST

START_TEST(test_s21_truncate_negate) {
  s21_decimal one = {{0u, 0u, 0u, 0u}, s21_NORMAL_VALUE};
  s21_decimal result = {{0u, 0u, 0u, 0u}, s21_NORMAL_VALUE};
  s21_decimal reference = {{0u, 0u, 0u, 0u}, s21_NORMAL_VALUE};
  s21_from_float_to_decimal(12.12, &one);
  s21_from_int_to_decimal(12, &reference);
  result = s21_truncate(one);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 1 TEST");
  s21_from_float_to_decimal(-12.12, &one);
  s21_from_int_to_decimal(-12, &reference);
  result = s21_truncate(one);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 2 TEST");
  s21_from_float_to_decimal(0.000012, &one);
  s21_from_int_to_decimal(0, &reference);
  result = s21_truncate(one);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 3 TEST");
  s21_from_float_to_decimal(12.12, &one);
  s21_from_float_to_decimal(-12.12, &reference);
  result = s21_negate(one);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 4 TEST");
  s21_from_float_to_decimal(-12.12, &one);
  s21_from_float_to_decimal(12.12, &reference);
  result = s21_negate(one);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 5 TEST");
  s21_from_float_to_decimal(0.000012, &one);
  s21_from_float_to_decimal(-0.000012, &reference);
  result = s21_negate(one);
  ck_assert_msg(s21_is_equal(result, reference) == 0, "FAIL 6 TEST");
}
END_TEST

Suite *suit_create(void) {
  Suite *suite = suite_create("Test's of s21_decimal");

  TCase *s21_truncate_negate = tcase_create("s21_truncate_negate test's");
  tcase_add_test(s21_truncate_negate, test_s21_truncate_negate);
  suite_add_tcase(suite, s21_truncate_negate);
  TCase *s21_add = tcase_create("s21_add test's");
  tcase_add_test(s21_add, test_s21_add);
  suite_add_tcase(suite, s21_add);
  TCase *s21_sub = tcase_create("s21_sub test's");
  tcase_add_test(s21_sub, test_s21_sub);
  suite_add_tcase(suite, s21_sub);
  TCase *s21_div = tcase_create("s21_div test's");
  tcase_add_test(s21_div, test_s21_div);
  suite_add_tcase(suite, s21_div);
  TCase *s21_mod = tcase_create("s21_mod test's");
  tcase_add_test(s21_mod, test_s21_mod);
  suite_add_tcase(suite, s21_mod);
  TCase *s21_mul = tcase_create("s21_mul test's");
  tcase_add_test(s21_mul, test_s21_mul);
  suite_add_tcase(suite, s21_mul);
  TCase *s21_floor = tcase_create("s21_floor test's");
  tcase_add_test(s21_floor, test_s21_floor);
  suite_add_tcase(suite, s21_floor);
  TCase *s21_round = tcase_create("s21_round test's");
  tcase_add_test(s21_round, test_s21_round);
  suite_add_tcase(suite, s21_round);
  TCase *s21_from_int_to_decimal =
      tcase_create("s21_from_int_to_decimal test's");
  tcase_add_test(s21_from_int_to_decimal, test_s21_from_int_to_decimal);
  suite_add_tcase(suite, s21_from_int_to_decimal);
  TCase *s21_from_decimal_to_int =
      tcase_create("s21_from_decimal_to_int test's");
  tcase_add_test(s21_from_decimal_to_int, test_s21_from_decimal_to_int);
  suite_add_tcase(suite, s21_from_decimal_to_int);
  TCase *s21_from_float_to_decimal =
      tcase_create("s21_from_float_to_decimal test's");
  tcase_add_test(s21_from_float_to_decimal, test_s21_from_float_to_decimal);
  suite_add_tcase(suite, s21_from_float_to_decimal);
  TCase *s21_is_less_is_greater = tcase_create("s21_is_less_is_greater test's");
  tcase_add_test(s21_is_less_is_greater, test_s21_is_less_is_greater);
  suite_add_tcase(suite, s21_is_less_is_greater);
  TCase *s21_is_lessOrEqual_is_greaterOrEqual =
      tcase_create("s21_is_lessOrEqual_is_greaterOrEqual test's");
  tcase_add_test(s21_is_lessOrEqual_is_greaterOrEqual,
                 test_s21_is_lessOrEqual_is_greaterOrEqual);
  suite_add_tcase(suite, s21_is_lessOrEqual_is_greaterOrEqual);
  TCase *s21_from_decimal_to_float =
      tcase_create("s21_from_decimal_to_float test's");
  tcase_add_test(s21_from_decimal_to_float, test_s21_from_decimal_to_float);
  suite_add_tcase(suite, s21_from_decimal_to_float);

  return suite;
}

int main(void) {
  Suite *suite = suit_create();
  SRunner *suite_runner = srunner_create(suite);
  srunner_run_all(suite_runner, CK_VERBOSE);
  srunner_free(suite_runner);

  if (srunner_ntests_failed(suite_runner) != 0) {
    return EXIT_FAILURE;
  }
  return EXIT_SUCCESS;
}
